GET http://localhost:8000/comments

GET http://localhost:8000/comments/1234

GET http://localhost:8000/comments?postID=1234

POST http://localhost:8000/comments
Content-Type: application/json

{
    "message": "Hello World",
    "sender": "Ido",
    "postID": "02291abb-8cff-491a-a3ae-3a8860a2a3a8"
}

PUT http://localhost:8000/comments/1234
Content-Type: application/json

{
    "message": "1234"
}

DELETE http://localhost:8000/comments/1234
Content-Type: application/json