GET http://localhost:8000/posts

GET http://localhost:8000/posts/1234

GET http://localhost:8000/posts?sender=Yoni

POST http://localhost:8000/posts
Content-Type: application/json

{
    "message": "Hello World",
    "sender": "Yoni"
}

PUT http://localhost:8000/posts/1234
Content-Type: application/json

{
    "message": "Good Afternoon"
}
