import { LanguageOption } from "../types/language-option";

export const supportedLanguages: readonly LanguageOption[] = [
  { code: "GB", label: "English", value: "ENGLISH" },
  { code: "IL", label: "עברית", value: "HEBREW" },
  { code: "SA", label: "العربية", value: "ARABIC" },
  { code: "RU", label: "Русский", value: "RUSSIAN" },
  { code: "FR", label: "Français", value: "FRENCH" },
  { code: "ES", label: "Español", value: "SPANISH" },
  { code: "CN", label: "普通话", value: "MANDARIN CHINESE" },
  { code: "BG", label: "Български", value: "BULGARIAN" },
  { code: "HR", label: "Croatian", value: "CROATIAN" },
  { code: "CZ", label: "Czech", value: "CZECH" },
  { code: "DK", label: "Dansk", value: "DANISH" },
  { code: "NL", label: "Nederlands", value: "DUTCH" },
  { code: "EE", label: "Estonian", value: "ESTONIAN" },
  { code: "IR", label: "فارسی", value: "FARSI" },
  { code: "DE", label: "Deutsch", value: "GERMAN" },
  { code: "GR", label: "ελληνικά", value: "GREEK" },
  { code: "IN", label: "हिन्दी", value: "HINDI" },
  { code: "HU", label: "Hungarian", value: "HUNGARIAN" },
  { code: "IT", label: "Italiano", value: "ITALIAN" },
  { code: "JP", label: "日本語", value: "JAPANESE" },
  { code: "KR", label: "한국어", value: "KOREAN" },
  { code: "LT", label: "Lithuanian", value: "LITHUANIAN" },
  { code: "LV", label: "Latvian", value: "LATVIAN" },
  { code: "NO", label: "Norsk", value: "NORWEGIAN" },
  { code: "PL", label: "Polski", value: "POLISH" },
  { code: "PT", label: "Português", value: "PORTUGUESE" },
  { code: "RO", label: "Romanian", value: "ROMANIAN" },
  { code: "RS", label: "Serbian", value: "SERBIAN" },
  { code: "SI", label: "Slovenščina", value: "SLOVENIAN" },
  { code: "SK", label: "Slovenčina", value: "SLOVAK" },
  { code: "SE", label: "Svenska", value: "SWEDISH" },
  { code: "TH", label: "ภาษาไทย", value: "THAI" },
  { code: "TR", label: "Türkçe", value: "TURKISH" },
  { code: "UA", label: "Українська", value: "UKRANIAN" },
  { code: "PK", label: "اُردُو", value: "URDU" },
  { code: "VN", label: "Tiếng Việt", value: "VIETNAMESE" },
];
