import { LanguageOption } from "../types/language-option";

export const supportedLanguages: readonly LanguageOption[] = [
  { code: "GB", label: "English", value: "ENGLISH", direction: "ltr" },
  { code: "IL", label: "עברית", value: "HEBREW", direction: "rtl" },
  { code: "SA", label: "العربية", value: "ARABIC", direction: "rtl" },
  { code: "RU", label: "Русский", value: "RUSSIAN", direction: "ltr" },
  { code: "FR", label: "Français", value: "FRENCH", direction: "ltr" },
  { code: "ES", label: "Español", value: "SPANISH", direction: "ltr" },
  { code: "CN", label: "普通话", value: "MANDARIN", direction: "ltr" },
  { code: "BG", label: "Български", value: "BULGARIAN", direction: "ltr" },
  { code: "HR", label: "Croatian", value: "CROATIAN", direction: "ltr" },
  { code: "CZ", label: "Czech", value: "CZECH", direction: "ltr" },
  { code: "DK", label: "Dansk", value: "DANISH", direction: "ltr" },
  { code: "NL", label: "Nederlands", value: "DUTCH", direction: "ltr" },
  { code: "EE", label: "Estonian", value: "ESTONIAN", direction: "ltr" },
  { code: "IR", label: "فارسی", value: "FARSI", direction: "rtl" },
  { code: "DE", label: "Deutsch", value: "GERMAN", direction: "ltr" },
  { code: "GR", label: "ελληνικά", value: "GREEK", direction: "ltr" },
  { code: "IN", label: "हिन्दी", value: "HINDI", direction: "ltr" },
  { code: "HU", label: "Hungarian", value: "HUNGARIAN", direction: "ltr" },
  { code: "IT", label: "Italiano", value: "ITALIAN", direction: "ltr" },
  { code: "JP", label: "日本語", value: "JAPANESE", direction: "ltr" },
  { code: "KR", label: "한국어", value: "KOREAN", direction: "ltr" },
  { code: "LT", label: "Lithuanian", value: "LITHUANIAN", direction: "ltr" },
  { code: "LV", label: "Latvian", value: "LATVIAN", direction: "ltr" },
  { code: "NO", label: "Norsk", value: "NORWEGIAN", direction: "ltr" },
  { code: "PL", label: "Polski", value: "POLISH", direction: "ltr" },
  { code: "PT", label: "Português", value: "PORTUGUESE", direction: "ltr" },
  { code: "RO", label: "Romanian", value: "ROMANIAN", direction: "ltr" },
  { code: "RS", label: "Serbian", value: "SERBIAN", direction: "ltr" },
  { code: "SI", label: "Slovenščina", value: "SLOVENIAN", direction: "ltr" },
  { code: "SK", label: "Slovenčina", value: "SLOVAK", direction: "ltr" },
  { code: "SE", label: "Svenska", value: "SWEDISH", direction: "ltr" },
  { code: "TH", label: "ภาษาไทย", value: "THAI", direction: "ltr" },
  { code: "TR", label: "Türkçe", value: "TURKISH", direction: "ltr" },
  { code: "UA", label: "Українська", value: "UKRANIAN", direction: "ltr" },
  { code: "PK", label: "اُردُو", value: "URDU", direction: "rtl" },
  { code: "VN", label: "Tiếng Việt", value: "VIETNAMESE", direction: "ltr" },
];
